monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: grouped
            grouped:
                type: group
                members: [streamed, deduplicated]
            streamed:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
            deduplicated:
                type: deduplication
                handler: symfony_mailer
            symfony_mailer:
                type: symfony_mailer
                from_email: 'noreply@olivia-gdpr-arc.eu'
                to_email: 'dfilipovi@foi.unizg.hr'
                subject: 'Olivia Error! %%message%%'
                level: critical
                formatter: monolog.formatter.html
                content_type: text/html
