twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        locale_default: '%locale.default%'
        locale_alternate: '%locale.alternate%'
        registration_enabled: '%registration.enabled%'

when@test:
    twig:
        strict_variables: true
