twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        locale_default: '%locale.default%'
        locale_alternate: '%locale.alternate%'
        videoUrl:
            topic:
                index: '%video.topic.index%'

when@test:
    twig:
        strict_variables: true
