twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        locale_default: '%locale.default%'
        locale_alternate: '%locale.alternate%'
        app_hostname: '%app.hostname%'

when@test:
    twig:
        strict_variables: true
