monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: grouped
        grouped:
            type: group
            members: [streamed, deduplicated]
        streamed:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        deduplicated:
            type: deduplication
            handler: symfony_mailer
        symfony_mailer:
            type: symfony_mailer
            from_email: 'noreply.olivia@foi.hr'
            to_email: 'dfilipovi@foi.unizg.hr'
            subject: 'Olivia Error! %%message%%'
            level: critical
            formatter: monolog.formatter.html
            content_type: text/html